language: node_js
node_js:
  - 6
  - 10
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
  - yarn build-storybook
deploy:
  provider: surge
  project: ./build/
  domain: lapskaus.surge.sh
  skip_cleanup: true
after_success:
  - npm run report-coverage
notifications:
  slack:
    on_success: change
    on_failure: change
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload